name: .NET Core Desktop

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    # Deploy project to Server
    - name: Deploy project to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "source/"
     
    # Restore project     
    - name: Restore project
      run: dotnet restore

    # Build project  
    - name: Build project
      run: dotnet build
          
    # Execute run script       
    - name: Execute run script
      run: RUNNER_TRACKING_ID="" && chmod u+r+x build-run.sh && ./build-run.sh #https://github.com/actions/runner/issues/598