name: .NET Core Desktop

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
     
    # Restore project     
    - name: Restore project
      run: dotnet restore

    # Build project  
    - name: Build project
      run: dotnet build --configuration Release
      
    # Kill dotnet process  
    - name: Kill dotnet process
      run: pkill dotnet   

    # # log     
    # - name: log
    #   shell: bash
    #   with: # Set the secret as an input
    #     SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    #   run: |
    #      echo $SECRET_PASSPHRASE

    # # log2     
    # - name: log2
    #   shell: bash
    #   with: # Set the secret as an input
    #     SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    #   run: |
    #      echo "$SECRET_PASSPHRASE"

    # log3
    - name: log3
      shell: bash
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      run: |
        echo "$SECRET_PASSPHRASE"

    # log3
    - name: log3
      shell: bash
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      run: |
        echo $SECRET_PASSPHRASE