name: .NET Core Desktop

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
      # Run build&run script
    - name: Run build&run script
      run: (chmod u+r+x build-run.sh && ./build-run.sh) &            
    #- name: Deploy project to Server
    #  uses: easingthemes/ssh-deploy@main
    #  env:
    #      SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
    #      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #      REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #      TARGET: "app/"
